# Generated by Django 3.2.19 on 2023-07-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='main_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='wording_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='writing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
