# Generated by Django 3.2.19 on 2023-07-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_colors'),
        ('checkout', '0005_auto_20230704_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='main_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_color_lineitems', to='products.color'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='wording_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wording_color_lineitems', to='products.color'),
        ),
    ]
