# Generated by Django 3.2.19 on 2023-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20230613_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
    ]
