# Generated by Django 3.2.19 on 2023-06-29 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230624_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_color_products', to='products.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='wording_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wording_color_products', to='products.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='writing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CustomizableProduct',
        ),
    ]
